### ISSUE TITLE
Cronjob example

### ISSUE THREAD

**Issue by adrenalinmike** [anantgarg/socialturn#12]
Is there an  example what kind of cron job this is supposed to be?
Create a cronjob and call yoursite.com/cron/suggestions once a day and yoursite.com/cron/post every 5 minutes

eg: *  * * * *  root php /xxxx/xxx/xxx.php 

couldn't find any usable command.

**Comment by anantgarg** [comment]
You can use a service like easycron.com for this if you are unable to setup the cronjob on your server.

**Comment by adrenalinmike** [comment]
Sorry but this does not answer my question, when I schedule a url like http://my.server.url/cron/post or .../suggestions nothing happens.  No posts no suggestions. I use an  web cron so this is not the issue,  and as status code i receive 200 OK .  the .htaccess is available and executed.
