### ISSUE TITLE
Error Http 500 when I signed up 

### ISSUE THREAD

**Issue by tungvision** [anantgarg/socialturn#14]
Hi,

When I signed up, I saw this message:"This page isn’t working scheduling.tungvision.com is currently unable to handle this request. HTTP ERROR 500"

How to resolve it? Thank you so much!
![http error 500](https://user-images.githubusercontent.com/46647588/51085570-18b70600-176e-11e9-8b37-b2037313e301.png)

**Comment by anantgarg** [comment]
Please check your error log for more information.

**Comment by tungvision** [comment]
Hi anantgarg, Thank you!14.01.2019, 02:19, "anantgarg" <notifications@github.com>:Please check your error log fir more information.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

-- Sincerely, Tung Le(84)983927482admin@tungvision.com

**Comment by tungvision** [comment]
Hi, 

Information in error log:
"[13-Jan-2019 16:18:58 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'scheduling.users' doesn't exist' in  /controllers/users.php:64

Stack trace:
#0 
/controllers/users.php(64): PDOStatement->execute(Array)
#1 [internal function]: validate()
#2 
/index.php(86): call_user_func('validate')
#3 {main}
  thrown in 
controllers/users.php on line 64"

Please help me to resolve this issues. Thank you!

**Comment by anantgarg** [comment]
Please execute the text files present in `db` folder in mySQL.
